server:
  servlet:
    context-path: /api/spring-security-example/

spring:
  #  jpa:
  #    database-platform: org.hibernate.dialect.PostgreSQLDialect
  #    hibernate:
  #      ddl-auto: update
  #    show-sql: true
  #    properties:
  #      hibernate.format_sql: true

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

  security:
    encrypt-strength: 6
    pub-key: classpath:pub.key
    private-key: classpath:private.key
    issuer: spring-boot-security-util-example
    stackTraceLogEnable: true
    jwtExpirationTime: 144000000
    openUrl:
      - "/users/create"
      - "/swagger-resources/**"
      - "/swagger-ui.html/**"
      - "/swagger-config/**"
      - "/authorization"
      - "/swagger-ui/**"
      - "/favicon.ico/**"
      - "/v3/api-docs/**"
      - "/v3/api-docs"
      - "/webjars/**"
      - "/swagger/**"
      - "/assets/**"
      - "/csrf/**"
      - "/docs/**"
      - "/error"
