#!/bin/bash

projectPath=$(pwd)

buildPath="$projectPath/build"

if [[ ! -d "$buildPath" ]]; then
    mkdir -p "$buildPath"
fi

cd "$buildPath" || exit 1

jsonLoggerPath="$buildPath/json-logger"

if [[ ! -d "$jsonLoggerPath" ]]; then
  git clone https://github.com/eliasmeireles/json-logger.git
fi

cd "$jsonLoggerPath" || exit 1

make local-publish

