name: Main testing

on:
  push:
    branches:
      - "*/**"
jobs:
  validation:
    name: "Build validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Test run
        run: |
          make test
      - name: Publish Local
        run: |
          make local-publish
