name: Main testing

on:
  push:
    branches:
      - main
jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Test run
        run: |
          make update
          make test
