name: Main testing

on:
  push:
    branches:
      - main
jobs:
  validation:
    name: "Build validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '19'

      - name: Test run
        run: |
          make update
          make test
      - name: Publish Local
        run: |
          make local-publish
